package Lab3;
import java.awt.Color;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class Bai1 extends javax.swing.JFrame {
    public Bai1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grColor = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMain = new javax.swing.JTextArea();
        txtFpoly = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnNew = new javax.swing.JMenuItem();
        mnOpen = new javax.swing.JMenuItem();
        mnSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rdbRed = new javax.swing.JRadioButtonMenuItem();
        rdbGreen = new javax.swing.JRadioButtonMenuItem();
        rdbBlue = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnTextColor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAboutUs = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNew.setBackground(new java.awt.Color(242, 242, 242));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconApplication/Notes.png"))); // NOI18N
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconApplication/User.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMargin(new java.awt.Insets(15, 15, 15, 15));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        btnExit.setBackground(new java.awt.Color(242, 242, 242));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconApplication/Exit.png"))); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMargin(new java.awt.Insets(15, 15, 15, 15));
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        txtMain.setColumns(20);
        txtMain.setRows(5);
        txtMain.setText("Uống nước nhờ nguồn\n");
        jScrollPane1.setViewportView(txtMain);

        txtFpoly.setEditable(false);
        txtFpoly.setBackground(new java.awt.Color(0, 153, 51));
        txtFpoly.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFpoly.setForeground(new java.awt.Color(0, 0, 0));
        txtFpoly.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFpoly.setText("Fpoly - Java 2");

        jMenu1.setText("File");

        mnNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconApplication/Notes.png"))); // NOI18N
        mnNew.setText("New");
        mnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNewActionPerformed(evt);
            }
        });
        jMenu1.add(mnNew);

        mnOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconApplication/Open_folder.png"))); // NOI18N
        mnOpen.setText("Open");
        mnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenActionPerformed(evt);
            }
        });
        jMenu1.add(mnOpen);

        mnSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconApplication/Save.png"))); // NOI18N
        mnSave.setText("Save");
        mnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveActionPerformed(evt);
            }
        });
        jMenu1.add(mnSave);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        grColor.add(rdbRed);
        rdbRed.setSelected(true);
        rdbRed.setText("Red");
        rdbRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRedActionPerformed(evt);
            }
        });
        jMenu2.add(rdbRed);

        grColor.add(rdbGreen);
        rdbGreen.setText("Green");
        rdbGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbGreenActionPerformed(evt);
            }
        });
        jMenu2.add(rdbGreen);

        grColor.add(rdbBlue);
        rdbBlue.setText("Blue");
        rdbBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbBlueActionPerformed(evt);
            }
        });
        jMenu2.add(rdbBlue);
        jMenu2.add(jSeparator1);

        btnTextColor.setText("Text Color");
        btnTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextColorActionPerformed(evt);
            }
        });
        jMenu2.add(btnTextColor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("System");

        mnAboutUs.setText("About us");
        mnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutUsActionPerformed(evt);
            }
        });
        jMenu3.add(mnAboutUs);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu3.add(mnExit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(txtFpoly)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFpoly, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNewActionPerformed
        // TODO add your handling code here:
        txtMain.setText("");
    }//GEN-LAST:event_mnNewActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtMain.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void mnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser luaChon = new JFileChooser();
        int ketQua = luaChon.showOpenDialog(null);
        if(ketQua == JFileChooser.APPROVE_OPTION){
            try {
                txtMain.setText("file:///"+ luaChon.getSelectedFile().getPath());
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_mnOpenActionPerformed

    private void mnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveActionPerformed
        // TODO add your handling code here:
        JFileChooser luaChon = new JFileChooser();
        int ketQua = luaChon.showSaveDialog(null);
        if(ketQua == JFileChooser.APPROVE_OPTION){
            File tenFile = luaChon.getSelectedFile();
            if(!tenFile.getName().endsWith(".txt")){
                tenFile = new File(tenFile.getPath()+".txt");
            }
            try {
                PrintWriter pw = new PrintWriter(tenFile);
                pw.println(txtMain.getText());
                pw.close();
            } catch (Exception e) {
            }
        }
        
    }//GEN-LAST:event_mnSaveActionPerformed

    private void rdbRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRedActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.RED);
    }//GEN-LAST:event_rdbRedActionPerformed

    private void rdbGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbGreenActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.GREEN);
    }//GEN-LAST:event_rdbGreenActionPerformed

    private void rdbBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbBlueActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.BLUE);
    }//GEN-LAST:event_rdbBlueActionPerformed

    private void btnTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextColorActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Chon mau", Color.BLACK);
        txtFpoly.setForeground(c);
    }//GEN-LAST:event_btnTextColorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "La Ngoc Hung","Gioi thieu",1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutUsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "La Ngoc Hung","Gioi thieu",1);
    }//GEN-LAST:event_mnAboutUsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JMenuItem btnTextColor;
    private javax.swing.ButtonGroup grColor;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnAboutUs;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnNew;
    private javax.swing.JMenuItem mnOpen;
    private javax.swing.JMenuItem mnSave;
    private javax.swing.JRadioButtonMenuItem rdbBlue;
    private javax.swing.JRadioButtonMenuItem rdbGreen;
    private javax.swing.JRadioButtonMenuItem rdbRed;
    private javax.swing.JTextField txtFpoly;
    private javax.swing.JTextArea txtMain;
    // End of variables declaration//GEN-END:variables
}
